config/routes.rb
Rails.application.routes.draw do
  resources :clearance_batches, only: [:index, :create, :show, :update]
  root to: "clearance_batches#index"
end

app/models/clearance_batch.rb
class ClearanceBatch < ActiveRecord::Base

  def title
    self.active ? "Active Batch #{self.id}" : "Batch #{self.id}"
  end


  has_many :items

  scope :active, -> { includes(:items).where(active: true).order(updated_at: :desc) }
  scope :completed, -> { includes(:items).where(active: false).order(updated_at: :desc) }

  def sort_items_by(attr, desc = false)
    desc ? items.order("#{attr} desc") : items.order("#{attr}")
  end

end

app/models/item.rb
class Item < ActiveRecord::Base

  CLEARANCE_PRICE_PERCENTAGE  = BigDecimal.new("0.75")

  belongs_to :style
  belongs_to :clearance_batch, optional: true, touch: true

  validates_presence_of :size, :color, :status

  scope :sellable, -> { where(status: 'sellable') }

  def clearance!
    # NOTE: Your original code failed to set sold_at correctly. This seemed like the place to do it.
    update_attributes!(status: 'clearanced',
                       price_sold: style.wholesale_price * CLEARANCE_PRICE_PERCENTAGE,
                       sold_at: DateTime.now)
  end

end

app/models/style.rb
class Style < ActiveRecord::Base
  self.inheritance_column = :_type_disabled
  has_many :items
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/clearance_batches_controller.rb
# NOTE: DEBUGGER
system 'clear'

class ClearanceBatchesController < ApplicationController


  # NOTE: Split batches into two groups for active and completed
  # Started out with several Ajax views but ultimately decided things were small
  # enough to simply re-render index asynchronously
  def index
    @active_batches = ClearanceBatch.active
    @completed_batches  = ClearanceBatch.completed

    respond_to do |format|
      format.html
      format.js
    end
  end

  def show
    @clearance_batch = ClearanceBatch.includes(:items).find(params[:id])
    @sort_options = {
      'id-asc' => {attr: 'id', text: 'ID UP'},
      'id-desc' => {attr: 'id', text: 'ID DN', desc: true},
      'size-asc' => {attr: 'size', text: 'Size UP'},
      'size-desc' => {attr: 'size', text: 'Size DN', desc: true},
      'color-asc' => {attr: 'color', text: 'Color UP'},
      'color-desc' => {attr: 'color', text: 'Color DN', desc: true},
      'price-asc' => {attr: 'price_sold', text: 'Price UP'},
      'price-desc' => {attr: 'price_sold', text: 'Price DN', desc: true},
      'style-asc' => {attr: 'style_id', text: 'Style UP'},
      'style-desc' => {attr: 'style_id', text: 'Style DN', desc: true},
      'date-asc' => {attr: 'sold_at', text: 'Date UP'},
      'date-desc' => {attr: 'sold_at', text: 'Date DN', desc: true},
      'updated-at-asc' => {attr: 'updated_at', text: 'Updated UP'},
      'updated-at-desc' => {attr: 'updated_at', text: 'Updated DN', desc: true},
    }

    @select_options = []
    @sort_options.keys.map { |e| @select_options << [@sort_options[e][:text], e] }

    if @clearance_batch
      @items = what_the_sort(@clearance_batch, clearance_params[:sort])
      respond_to do |format|
        format.html
        format.csv
        format.js
        format.pdf do
          render pdf: "clearance_batch_#{@clearance_batch.id}",
                 template: 'clearance_batches/_report.html.erb',
                 layout: 'pdf.html',
                 title: "clearance_batch_#{@clearance_batch.id}"
        end
      end
    else
      # NOTE: Handle NOT FOUND
    end
  end

  # NOTE: handles create for csv and item into a batch.
  # feel kinda icky about the nonRESTfullness but didn't feel
  # an Items controller was the solution either
  def create

    # CSV or batch ID required - batch_id may be 'new'
    # Item ID or batch ID required
    if !clearance_params[:csv_file] && ( clearance_params[:item_id] == '' || !clearance_params[:item_id] )
      flash[:alert] = "You must enter an Item id or CSV file to clearance items"
    else
      # ClearancinService will figure out what to do with our input.
      service = ClearancingService.new(
        file: clearance_params[:csv_file],
        item_id: clearance_params[:item_id],
        batch: ClearanceBatch.find_by(id: clearance_params[:batch_id])).execute!
      # CSV batches are automatically closed after processing.
      if service.batch.persisted? && clearance_params[:csv_file]
        service.batch.update_attributes(active: false)
      end

      # Put together various flash msgs for after action report.
      flash[:alert] = service.errors.join("<br/>") if service.errors.any?
      flash[:notice] = service.notices.join("<br/>") if service.notices.any?
    end
    redirect_to action: :index
  end

  def update
    batch = ClearanceBatch.find_by(id: params[:id])

    # No valid batch passed
    if !batch
      flash[:alert] = "Could not find batch id #{params[:id]}."

    # Attempting to close an already closed batch
    elsif !batch.active && clearance_params[:close_batch]
      flash[:alert] = "Batch id #{params[:id]} is already closed."

    # Attempting to open an already active branch
    elsif batch.active && clearance_params[:activate_batch]
      flash[:alert] = "Batch id #{params[:id]} is already open."

    # Close Success Case
    elsif clearance_params[:close_batch]
      batch.update_attributes(active: false)
      flash[:notice] = "Clearance Batch #{batch.id} successfully closed."

    # Activated Success Case
    elsif clearance_params[:activate_batch]
      batch.update_attributes(active: true)
      flash[:notice] = "Clearance Batch #{batch.id} reactivated."

    # Fallthrough catch flashes general error
    else
      flash[:alert] = "Failed to update batch #{params[:id]}, refresh and try again."

    end

    redirect_to action: :index
  end

  private

  # NOTE: Added Strong params because..... That's what you do. :-)
  def clearance_params
    params.permit(:csv_file, :item_id, :batch_id, :close_batch, :activate_batch, :sort)
  end

  def what_the_sort(batch, sort)
    sort ||= 'updated-at-desc'
    return batch.sort_items_by(@sort_options[sort][:attr], @sort_options[sort][:desc])
    # case sort
    # when 'id_asc'
    #   return batch.sort_items_by('id')
    # when 'id-desc'
    #   return batch.sort_items_by('id', true)
    # else
    #   return batch.sort_items_by('updated_at', true)
    # end
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/clearance_batch_helper.rb
require 'csv'

module ClearanceBatchHelper

  def generate_csv_report(items)
    attrs = csv_headers(items.first)
    CSV.generate(headers: true) do |row|
      row << attrs
      items.each do |item|
        row << csv_attrs(item).values
      end
    end
  end

end

app/helpers/item_helper.rb
module ItemHelper

  def csv_headers(item)
    csv_attrs(item).keys
  end

  def csv_attrs(item)
    {'id' => item.id,
     'size' => item.size,
     'color' => item.color,
     'price_sold' => ActionController::Base.helpers.number_to_currency(item.price_sold),
     'style' => item.style.name,
     'date_sold' => ActionController::Base.helpers.l(item.sold_at, format: :short),
     'status' => item.status}
  end

end

app/views/application/_help.html.erb
<div id='help-container' class='container'>
  <div class='row'>
    <div class='col-md-6'>
      <h5 class='text-center'>CSV Batch:</h5>
      <ul>
        <li>Clearance a collection of items by uploading a CSV file.</li>
        <li>Choose a file from your computer and click 'Clearance CSV'</li>
        <li>CSV batches are automatically closed. IE Not Active. </br>Click 'Reopen' to add additional items to this batch.</li>
        <li>You will see a message detailing the outcome of your file.</li>
      </ul>
      <h5 class='text-center'>General:</h5>
      <ul>
        <li>Completed batch details can be viewed in HTML, PDF, and CSV</li>
        <li>The data in all three reports match.</li>
        <li>Using IE6, No Problem! All site functions work without javascript.</li>
        <li>Click the help icon again to remove this help box.</li>
      </ul>
    </div>
    <div class='col-md-6'>
      <h5 class='text-center'>Single Item:</h5>
      <ul>
        <li>Clearanace a single item
          <ul>
            <li>Enter the Item ID (number)</li>
            <li>Select a batch to add to from the dropdown (optional)</li>
            <li>Hit return or click 'Clearance Item!'</li>
          </ul>
        </li>
        <li>Dropdown will always default to the last updated batch</li>
         <li>Dropdown contains an option for 'New Batch'</li>
        <li>To close out a batch, click 'Complete'.</li>
        <li>A batch must be 'Active' to receive additional clearance Items.</li>
        <li>Once completed, a batch may be reactivated if needed.</li>
        <li>No Clicks! Input form resets after each item. </br>You just keep scanning!</li>
      </ul>
    </div>
  </div>
  <h6 class='text-center'>If you have any questions or suggestions which might improve your experience.</h6>
  <h6 class='text-center'>Please contact <%= mail_to 'bootcoder@hunters_fictional_support.co' %></h6>

</div>

app/views/application/_notifications.html.erb
<div id='notifications' class='container'>
  <%- if flash[:notice] -%>
    <div class="alert alert-info" role="alert">
      <%= flash[:notice].html_safe %>
    </div>
  <%- end -%>
  <%- if flash[:alert] -%>
    <div class="alert alert-danger" role="alert">
      <%= flash[:alert].html_safe %>
    </div>
  <%- end -%>
</div>

app/views/clearance_batches/_active_buttons.html.erb
<div class='btn-group'>
  <%= button_to 'View', clearance_batch_path(batch), class: 'active-button html-btn btn btn-info', method: 'get' %>
  <%= button_to 'Complete', clearance_batch_path(batch), class: 'active-button close-btn btn btn-success', name: 'close_batch', remote: true, method: :patch %>
</div>

app/views/clearance_batches/_completed_buttons.html.erb
<div class='btn-group'>
  <%= button_to "View", clearance_batch_path(batch), method: :get, class: 'completed-btn html-btn btn btn-info'  %>
  <%= button_to "Reopen", clearance_batch_path(batch), method: :patch, name: 'activate_batch', remote: true, class: 'completed-btn open-btn btn btn-warning'  %>
</div>
<div class='btn-group'>
  <%= button_to "PDF", clearance_batch_path(batch, format: :pdf), method: :get, class: 'completed-btn pdf-btn btn btn-secondary'  %>
  <%= button_to "CSV", clearance_batch_path(batch, format: :csv), method: :get, class: 'completed-btn csv-btn btn btn-secondary'  %>
</div>

app/views/clearance_batches/_in_progress_batches.html.erb
<div class='in_progress_batches_container container'>
  <h3 id='in_progress_batches_title'>In Progress Batches</h3>
  <table class="table table-striped in_progress_batches">
    <thead class='text-center'>
      <tr>
        <th scope='col' style="width: 25%">ID</th>
        <th scope='col' style="width: 25%">Date Updated</th>
        <th scope='col' style="width: 25%">Total Items</th>
        <th scope='col' style="width: 25%">Options</th>
      </tr>
    </thead>
    <tbody id="in_progress_rows">
      <% @in_progress_batches.each do |batch| %>
        <tr class='batch-row text-center'>
          <td scope='row'><%= batch.title %></td>
          <td><%= l(batch.updated_at, format: :short) %></td>
          <td><%= batch.items.count %></td>
          <td>
            <div class='btn-group'>
              <%= button_to 'View', clearance_batch_path(batch), class: 'report-btn html-btn btn btn-success', method: 'get' %>
              <%= button_to 'Complete', clearance_batch_path(batch), class: 'report-btn html-btn btn btn-warning', name: 'close_batch', remote: true, method: :patch %>
            </div>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/clearance_batches/_index_form.html.erb
<div class='container-fluid' id='index_form_container'>
  <%= form_with url: clearance_batches_path, multipart: true, id: 'index_form', class: 'form col-md-12', role: 'form' do |f| %>
    <div class='row'>

      <div class='form-group col-md-4'>
        <%= f.file_field 'csv_file', class: 'form-control-file form-control', accept: 'text/csv' %>
        <%= f.submit 'Clearance CSV!', id: 'submit_csv', class: 'form-control btn btn-info' %>
      </div>

      <div class='col-md-4 d-none d-sm-none d-md-block form-spacer text-center'>
        <p>CSV batch</p>
        <%= image_tag 'arrow.png', class: 'form-arrow reverse-arrow' %>
        <p>Single Item</p>
        <%= image_tag 'arrow.png', class: 'form-arrow' %>
      </div>

      <div class='form-group col-md-4'>
        <%= f.text_field 'item_id', id: 'item_id_input', class: 'form-control', placeholder: 'Single Item ID', autofocus: true, autocomplete: 'off' %>
        <% if @active_batches.any? %>
          <%= f.select 'batch_id', options_from_collection_for_select(@active_batches, :id, :title, @active_batches.first.id.to_s), {include_blank: 'New Batch'}, {id: 'batch_select', class: 'form-control'} %>
        <% else %>
          <%= f.select 'batch_id', ['New Batch'], {}, {class: 'form-control'} %>
        <% end %>
        <%= f.submit 'Clearance Item!', id: 'submit_item', class: 'form-control btn btn-info' %>
      </div>

    </div>
  <% end %>
</div>

app/views/clearance_batches/_report.html.erb
<div class='container'>
  <div class='row'>
    <table id='batch-report' class='table table-striped'>
      <thead class='thead-dark'>
        <th scope='col' >ID</th>
        <th scope='col' >Size</th>
        <th scope='col' >Color</th>
        <th scope='col' >Price Sold</th>
        <th scope='col' >Style</th>
        <th scope='col' >Date Sold</th>
        <th scope='col' >Status</th>
      </thead>
      <tbody>
        <% @items.each_with_index do |item, idx| %>
          <tr class="report-row">
            <th scope='row' ><%= item.id %></th>
            <td><%= item.size %></td>
            <td><%= item.color %></td>
            <td><%= number_to_currency(item.price_sold) %></td>
            <td><%= item.style.name %></td>
            <td><%= l(item.sold_at, format: :short) %></td>
            <td><%= item.status %></td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</div>

app/views/clearance_batches/_show.html.erb
<div class='container'>
  <div class='row'>
    <table id='batch-report' class='table table-striped'>
      <thead class='thead-dark'>
        <th scope='col' >ID</th>
        <th scope='col' >Size</th>
        <th scope='col' >Color</th>
        <th scope='col' >Price Sold</th>
        <th scope='col' >Style</th>
        <th scope='col' >Date Sold</th>
        <th scope='col' >Status</th>
      </thead>
      <tbody>
        <% @clearance_batch.items.each_with_index do |item, idx| %>
          <tr class="report-row">
            <th scope='row' ><%= item.id %></th>
            <td><%= item.size %></td>
            <td><%= item.color %></td>
            <td><%= number_to_currency(item.price_sold) %></td>
            <td><%= item.style.name %></td>
            <td><%= l(item.sold_at, format: :short) %></td>
            <td><%= item.status %></td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</div>

app/views/clearance_batches/_table.html.erb
<!-- Combining these two tables into one partial -->
<!-- was a good idea from a simplicity standpoint -->
<!-- I'm not pleased with readability as a result.. -->
<!-- Also Yes I agree, one should not ordinarily leave a comment in HTML -->

<% if table_state == 'completed' %>
  <h3 class='table-title text-success'>Completed Batches</h3>
<% else %>
  <h3 class='table-title text-danger'>Active Batches</h3>
<% end %>

<div class='table-container'>
  <table class="table table-responsive table-striped <%= table_state %>_table">
    <tbody class='table-body'>
      <%- batches.each do |batch| -%>
        <tr class='batch-row text-center'>
          <td scope='row'><%= batch.title %></td>
          <td><%= pluralize(batch.items.count, 'Item') %></td>
          <td><%= l(batch.updated_at, format: :short) %></td>
          <td>
            <% if table_state == 'completed' %>
              <%= render partial: 'completed_buttons', locals: {batch: batch} %>
            <% else %>
              <%= render partial: 'active_buttons', locals: {batch: batch} %>
            <% end %>
          </td>

        </tr>
      <%- end -%>
    </tbody>
  </table>
</div>

app/views/clearance_batches/index.html.erb
<div id='app_container'>

  <%= render partial: 'index_form' %>

  <div id='index_tables_container' class='container-fluid'>
    <div class='row'>

      <div id='active_table_container' class='col-md-6'>
        <%= render partial: 'table', locals: {batches: @active_batches, table_state: 'active'} %>
      </div>

      <div id='completed_table_container' class='col-md-6'>
        <%= render partial: 'table', locals: {batches: @completed_batches, table_state: 'completed'} %></div>
      </div>

    </div>
  </div>
</div>

app/views/clearance_batches/index.js.erb
$('#active_table_container').html("<%= j render partial: 'table', locals: {batches: @active_batches, table_state: 'active'} %>")
$('#completed_table_container').html("<%= j render partial: 'table', locals: {batches: @completed_batches, table_state: 'completed'} %>")
$('#index_form_container').replaceWith("<%= j render partial: 'index_form' %>")
$('#notifications').html("<%= j render partial: 'notifications' %>")
$('#index_form').trigger('reset')
$('#item_id_input').focus()

// NOTE: This grew as time went on,
// could just rerender index as a partial at this point
// but,,,,,ewwwwwww.

app/views/clearance_batches/show.csv.erb
<%= generate_csv_report(@clearance_batch.items) %>

app/views/clearance_batches/show.html.erb
<div id='report-header' class='alert alert-dark container'>
  <div class="row">
    <div class='col-md-6 text-center'>
      <h2>Clearance Batch Report:</h2>
      <h4>Batch ID: <%= @clearance_batch.id %> &nbsp; &nbsp; Total Items: <%= @clearance_batch.items.count %></h4>
    </div>
    <div class='col-md-3 text-center'>
      <h4>Export Options</h4>
      <div class='btn-group btn-group-lg' role='group'>
        <%= button_to "PDF", clearance_batch_path(@clearance_batch, format: :pdf), method: :get, class: 'completed-btn pdf-btn btn btn-primary'  %>
        <%= button_to "CSV", clearance_batch_path(@clearance_batch, format: :csv), method: :get, class: 'completed-btn csv-btn btn btn-primary'  %>
      </div>
    </div>
    <div class='col-md-3 text-center'>
      <h4>Sort by</h4>
      <%= form_with url: clearance_batch_path(@clearance_batch), method: :get, class: 'form-inline' do |f| %>
        <div class='form-group'>
          <%= f.select :sort, options_for_select(@select_options), {}, {class: 'form-control', id: 'sort-select'} %>
          <%= f.button '>', id: 'btn-sort-select', class: 'btn btn-primary' %>
        </div>
      <% end %>
    </div>
  </div>
</div>

<%= render partial: 'report' %>

app/views/clearance_batches/show.js.erb
$('#batch-report').parents('.container').replaceWith("<%= j render partial: 'report' %>")

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Stitch Fix Clearancing Tool</title>
  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= javascript_include_tag 'application' %>
  <%= favicon_link_tag 'stitch-fav.png' %>
  <%= csrf_meta_tags %>
</head>
<body>
<header class='container-fluid'>
  <div class='col-md-12'>
      <%= link_to image_tag('stitch.png', class: 'hero-img offset-col-6'), root_path %>
      <input type="checkbox" id='help-toggle'>
      <label for='help-toggle' class='help-label text-center'><%= image_tag 'help.png', class: 'btn-help offset-col-10' %></label>
      <%= render partial: 'help' %>
  </div>
</header>
<%= render partial: 'notifications' %>
<%= yield %>

</body>
</html>

app/views/layouts/pdf.html.erb
<!DOCTYPE html>
<html>
<head>
<title>PDF</title>
  <%= wicked_pdf_stylesheet_link_tag "application" -%>
</head>
<body>
  <div class='container'>
    <%= yield %>
  </div>
</body>
</html>